analyzer:
  language:
    strict-casts: false
    #    strict-inference: true
    strict-raw-types: true
  errors:
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
  exclude:
    - "bin/cache/**"
    - "build/**"
    - "**/*.g.dart"

formatter:
  page_width: 100

linter:
  rules:
    #    - prefer_relative_imports: false
    #    # Essentials
    - always_specify_types
    - annotate_overrides
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_final_fields
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_single_quotes
    - prefer_collection_literals
    - use_key_in_widget_constructors

    # Clean & Safe Code
    - avoid_returning_null_for_void
    - cancel_subscriptions
    - close_sinks
    - avoid_shadowing_type_parameters
    - avoid_return_types_on_setters
    - await_only_futures
    - no_logic_in_create_state
    - use_build_context_synchronously

    # Style & Formatting
    - sort_child_properties_last
    - always_use_package_imports
    - require_trailing_commas

    # Performance & Consistency
    - unnecessary_const
    - unnecessary_this
    - unnecessary_await_in_return
    - prefer_final_locals
    - prefer_typing_uninitialized_variables

